### PR TITLE
Multiple queries (alternate interface)

### PR DESCRIPTION
**Pull request by Masterchef365**
Allows one to make multiple queries from a single system. See the `multiple_queries` example!

This is a breaking change. Queries now have names; individual queries are declared like so:
```rust
sched
    .add_system(Self::update)
    .query(Query::new("My Query Name")
        .intersect::<MyComponent>(Access::Write))
    .query(Query::new("My Other Query Name")
        .intersect::<MyOtherComponent>(Access::Write))
    .build();
```

Queries are then referenced by their name:
```rust
for key in query.iter("My Query Name") {
    // ...
}
```

### CODE REVIEW

**Comment by MrKangs** [comment]
Why do we want to write the word Query twice to declare a query in general? 
```rust 
// Old System
.query("My Query Name")
```
 to 
 ```rust
// New System
 .query(Query::new("My Query Name"))
 ```

I can see why for the implementation of the rename for query with the reasoning of inside the library, but isn't there a different way to implement that does not make the user/developer to write the word "Query" twice?

**Review by MrKangs — COMMENTED** [review]
Why do we want to write the word Query twice to declare a query in general? 
```rust 
// Old System
.query("My Query Name")
```
 to 
 ```rust
// New System
 .query(Query::new("My Query Name"))
 ```

I can see why for the implementation of the rename for query with the reasoning of inside the library, but isn't there a different way to implement that does not make the user/developer to write the word "Query" twice?

If there is a good reason that we have to do with it, then I am fine with this implementation since I have tested it on my machine.

**Comment by Masterchef365** [comment]
> Why do we want to write the word Query twice to declare a query in general?

The reason for the change is that `Query` is useful as a data type that can be stored or manipulated, which is especially useful when making libraries. For example, one might have a library which provides a system, and that system may need a set of query parameters. The library can then have a function returning an appropriate `Query`. 

As for the interface, I'm flexible on that. This way was the most straightforward compared to our original interface, but another possible API would be:
```rust
sched.add_system(Self::my_system, &[
    Query::new("My Query Name")
        .intersect::<MyComponent>(Access::Write),
    Query::new("My Other Query Name")
        .intersect::<MyOtherComponent>(Access::Write)
]);
```

There are lots of other ways to do this, so if you have ideas let me know!

**Comment by MrKangs** [comment]
> > Why do we want to write the word Query twice to declare a query in general?
> 
> The reason for the change is that `Query` is useful as a data type that can be stored or manipulated, which is especially useful when making libraries. For example, one might have a library which provides a system, and that system may need a set of query parameters. The library can then have a function returning an appropriate `Query`.
> 
> As for the interface, I'm flexible on that. This way was the most straightforward compared to our original interface, but another possible API would be:
> 
> ```rust
> sched.add_system(Self::my_system, &[
>     Query::new("My Query Name")
>         .intersect::<MyComponent>(Access::Write),
>     Query::new("My Other Query Name")
>         .intersect::<MyOtherComponent>(Access::Write)
> ]);
> ```
> 
> There are lots of other ways to do this, so if you have ideas let me know!

I personally think that this implementation makes more sense that you are creating an array of queries that inserting that queries into the system call. However, would it be possible (and I think it is possible, but not sure if I am grammatically correct or not) to this implementation?

```rust

let my_system_quries = [Query::new("My Query Name").intersect::<MyComponent>(Access::Write),
Query::new("My Other Query Name").intersect::<MyOtherComponent>(Access::Write)];

sched.add_system(Self::my_system).add_qurery(my_system_quries).subsribe::<Component>().build();


```

**Review by MrKangs — APPROVED** [review]
As we discussed in the stand-up yesterday, we agree to move along with new implementation UI for quires. 
For example, the current implementation for this pull request will be the following.
```rust
let thing = sched.add_system(...)
  .query("query1", Query::new()
    .intersect::<Comp1>(Access::Write)
    .intersect::<Comp2>(Access::Read)
  )
  .query("query2", Query::new()
    .intersect::<Comp3>(Access::Read)
    .intersect::<Comp4>(Access::Write)
  );
```
However, we will implement a new UI like the following below
```rust
let thing = sched.add_system(...)
  .query("query1", stuff!(&mut Comp1, &Comp2))
  .query("query2", stuff!(&Comp3, &mut Comp4));
```
This implementation will address better UI for plugin development while able to store the Query as a datatype.

**Pull request merged**
